/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimeBanner: typeof import('./src/components/anime/AnimeBanner.vue')['default']
    AnimeCard: typeof import('./src/components/anime/AnimeCard.vue')['default']
    AnimeDescription: typeof import('./src/components/anime/AnimeDescription.vue')['default']
    AnimeGrid: typeof import('./src/components/anime/AnimeGrid.vue')['default']
    AnimeMetadata: typeof import('./src/components/anime/AnimeMetadata.vue')['default']
    AppearanceMenu: typeof import('./src/components/utils/AppearanceMenu.vue')['default']
    BackToListButton: typeof import('./src/components/navigation/BackToListButton.vue')['default']
    ClientOnly: typeof import('./src/components/utils/ClientOnly.vue')['default']
    Input: typeof import('@jtclarkjr/component-library-vue')['Input']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteTransition: typeof import('./src/components/utils/RouteTransition.vue')['default']
    ScrollToTop: typeof import('./src/components/utils/ScrollToTop.vue')['default']
    SearchFilters: typeof import('./src/components/search/SearchFilters.vue')['default']
    Select: typeof import('@jtclarkjr/component-library-vue')['Select']
  }
}

// For TSX support
declare global {
  const AnimeBanner: typeof import('./src/components/anime/AnimeBanner.vue')['default']
  const AnimeCard: typeof import('./src/components/anime/AnimeCard.vue')['default']
  const AnimeDescription: typeof import('./src/components/anime/AnimeDescription.vue')['default']
  const AnimeGrid: typeof import('./src/components/anime/AnimeGrid.vue')['default']
  const AnimeMetadata: typeof import('./src/components/anime/AnimeMetadata.vue')['default']
  const AppearanceMenu: typeof import('./src/components/utils/AppearanceMenu.vue')['default']
  const BackToListButton: typeof import('./src/components/navigation/BackToListButton.vue')['default']
  const ClientOnly: typeof import('./src/components/utils/ClientOnly.vue')['default']
  const Input: typeof import('@jtclarkjr/component-library-vue')['Input']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const RouteTransition: typeof import('./src/components/utils/RouteTransition.vue')['default']
  const ScrollToTop: typeof import('./src/components/utils/ScrollToTop.vue')['default']
  const SearchFilters: typeof import('./src/components/search/SearchFilters.vue')['default']
  const Select: typeof import('@jtclarkjr/component-library-vue')['Select']
}