/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimeBanner: typeof import('./src/components/AnimeBanner.vue')['default']
    AnimeCard: typeof import('./src/components/AnimeCard.vue')['default']
    AnimeDescription: typeof import('./src/components/AnimeDescription.vue')['default']
    AnimeGrid: typeof import('./src/components/AnimeGrid.vue')['default']
    AnimeMetadata: typeof import('./src/components/AnimeMetadata.vue')['default']
    ClientOnly: typeof import('./src/components/ClientOnly.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteTransition: typeof import('./src/components/RouteTransition.vue')['default']
    SearchFilters: typeof import('./src/components/SearchFilters.vue')['default']
  }
}

// For TSX support
declare global {
  const AnimeBanner: (typeof import('./src/components/AnimeBanner.vue'))['default']
  const AnimeCard: (typeof import('./src/components/AnimeCard.vue'))['default']
  const AnimeDescription: (typeof import('./src/components/AnimeDescription.vue'))['default']
  const AnimeGrid: (typeof import('./src/components/AnimeGrid.vue'))['default']
  const AnimeMetadata: (typeof import('./src/components/AnimeMetadata.vue'))['default']
  const ClientOnly: (typeof import('./src/components/ClientOnly.vue'))['default']
  const RouterLink: (typeof import('vue-router'))['RouterLink']
  const RouterView: (typeof import('vue-router'))['RouterView']
  const RouteTransition: (typeof import('./src/components/RouteTransition.vue'))['default']
  const SearchFilters: (typeof import('./src/components/SearchFilters.vue'))['default']
}
