/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimeBanner: typeof import('./src/components/AnimeBanner.vue')['default']
    AnimeCard: typeof import('./src/components/AnimeCard.vue')['default']
    AnimeDescription: typeof import('./src/components/AnimeDescription.vue')['default']
    AnimeGrid: typeof import('./src/components/AnimeGrid.vue')['default']
    AnimeMetadata: typeof import('./src/components/AnimeMetadata.vue')['default']
    ClientOnly: typeof import('./src/components/ClientOnly.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RouteTransition: typeof import('./src/components/RouteTransition.vue')['default']
    SearchFilters: typeof import('./src/components/SearchFilters.vue')['default']
  }
}
